### ISSUE TITLE
GNU Octave plotting using RcppOctave

### ISSUE THREAD

**Issue by iembry-USGS** [renozao/RcppOctave#10]
Hi, I am using GNU Octave 3.8.1 on a Trisquel GNU/Linux distribution. The GNU Octave code, below, is what I want to replicate using RcppOctave in R.

The operations that I am having trouble with are the various plotting functions (mesh, meshz, contour, etc.).

Can you tell me how to run this code using RcppOctave?

Thank you.

Irucka Embry

    rho = 1000
    g = 9.81
    r_cylinder = 15:5:40
    h = 25:5:50
    
    [r_cylinder_grid, h_grid] = meshgrid(r_cylinder, h);
    W_grid = rho*g*(pi*(r_cylinder_grid/1000).^2 .* h_grid);
    
    mesh(r_cylinder_grid, h_grid, W_grid);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    zlabel('W, N');
    
    meshz(r_cylinder_grid, h_grid, W_grid);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    zlabel('W, N');
    
    surf(r_cylinder_grid, h_grid, W_grid);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    zlabel('W, N');
    
    [C, hd1] = contour(r_cylinder_grid, h_grid, W_grid);
    clabel(C, hd1);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    
    plot(h_grid, W_grid);
    xlabel('h, m');
    ylabel('W, N');
    
    plot(r_cylinder_grid', W_grid')
    xlabel('r_{cylinder}, mm');
    ylabel('W, N');

**Comment by rabravo** [comment]
#This code execute normally on my machine with octave-3.8.0 and R version 3.2.0
#You can copy and paste directly into the R console. 
#Happy coding

library(RcppOctave)
RcppOctave::o_source(text="\
rho = 1000;\
g = 9.81;\
r_cylinder = 15:5:40;\
h = 25:5:50;\
\
[r_cylinder_grid, h_grid] = meshgrid(r_cylinder, h);\
W_grid = rho*g*(pi*(r_cylinder_grid/1000).^2 .* h_grid);\
mesh(r_cylinder_grid, h_grid, W_grid);\
xlabel('r_{cylinder}, mm');\
ylabel('h, m');\
zlabel('W, N');\
\
meshz(r_cylinder_grid, h_grid, W_grid);\
xlabel('r_{cylinder}, mm');\
ylabel('h, m');\
zlabel('W, N');\
\
surf(r_cylinder_grid, h_grid, W_grid);\
xlabel('r_{cylinder}, mm');\
ylabel('h, m');\
zlabel('W, N');\
\
[C, hd1] = contour(r_cylinder_grid, h_grid, W_grid);\
clabel(C, hd1);\
xlabel('r_{cylinder}, mm');\
ylabel('h, m');\
\
plot(h_grid, W_grid);\
xlabel('h, m');\
ylabel('W, N');\
\
print('figure_1.png', '-dpng');\
plot(r_cylinder_grid', W_grid')\
xlabel('r_{cylinder}, mm');\
ylabel('W, N');\
\
print('figure_2.png', '-dpng');
")

**Comment by renozao** [comment]
What happens is that Octave runs in non-interactive mode and the plot does not have the time to be plotted.
Essentially, a solution is to add `refresh` or `drawnow` commands where the plot is supposed to appear.

You can also use the `pause` command, but you then have to press `enter` in order to get back to `R`.

This said, I am pushing a fix for this now (in branch `develop`), so that plots are refreshed by default, after each call to `.CallOctave`, which is the workhorse function eventually called by all the interface functions.
Can you please try this version and confirm it works well for you?
Obviously, if you make multiple plots in a single call, only the last one will show up.

Thanks

**Comment by iembry-USGS** [comment]
Hi, thank you both!

rabravo, I was not able to use your code as is. I had to modify it before it worked. I also added a print command for each of the figures.

The revised code is below:

    library(RcppOctave)
    o_source(text = "
    rho = 1000
    g = 9.81
    r_cylinder = 15:5:40
    h = 25:5:50
    
    [r_cylinder_grid, h_grid] = meshgrid(r_cylinder, h);
    W_grid = rho*g*(pi*(r_cylinder_grid/1000).^2 .* h_grid);
    
    mesh(r_cylinder_grid, h_grid, W_grid);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    zlabel('W, N');
    
    print('mesh.png', '-dpng');
    
    meshz(r_cylinder_grid, h_grid, W_grid);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    zlabel('W, N');
    
    print('meshz.png', '-dpng');
    
    surf(r_cylinder_grid, h_grid, W_grid);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    zlabel('W, N');
    
    print('surf.png', '-dpng');
    
    [C, hd1] = contour(r_cylinder_grid, h_grid, W_grid);
    clabel(C, hd1);
    xlabel('r_{cylinder}, mm');
    ylabel('h, m');
    
    print('contour.png', '-dpng');
    
    plot(h_grid, W_grid);
    xlabel('h, m');
    ylabel('W, N');
    
    print('figure_1.png', '-dpng');
    
    plot(r_cylinder_grid', W_grid')
    xlabel('r_{cylinder}, mm');
    ylabel('W, N');
    
    print('figure_2.png', '-dpng');
    ")

Thank you both.
