### ISSUE TITLE
Call Octave functions from Rcpp

### ISSUE THREAD

**Issue by bhattaa** [renozao/RcppOctave#13]
Is there a way to call Octave functions directly from Rcpp rather than calling an R function which calls on to RcppOctave?

For the latter, see
http://stackoverflow.com/questions/21225662/calling-a-user-defined-r-function-from-c-using-rcpp

**Comment by renozao** [comment]
Example using inline:

```R
feval <- RcppOctave:::rcppoctave(signature(), '
Rcpp::List args = Rcpp::List::create(10);
SEXP result = CallOctave("rand", args);
return(result);

set.seed(1)
res1 <- .O$rand(10)
set.seed(1)
res2 <- feval()
identical(res1, res2)
```

**Comment by renozao** [comment]
Can you please tell me if this is working for you?

**Comment by bhattaa** [comment]
Sorry I have been away. I will check today or tomorrow and let you know.

Thanks,

Arnab

**Comment by renozao** [comment]
This should be working. Closing the issue.
