### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by meisamhe** [renozao/RcppOctave#4]
I followed the instructions to install on windows, yet it was unsuccessful. It through the following error:
Installing package into ‘C:/Users/MeisamHe/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
* installing *source* package 'RcppOctave' ...
** package 'RcppOctave' successfully unpacked and MD5 sums checked
Loading autoconf-like macros for Windows... OK
Package RcppOctave - version 0.14.5
Checking Rscript version... cygwin warning:
  MS-DOS style path detected: C:/PROGRA~1/R/R-31~1.2/bin/x64/Rscript.exe
  Preferred POSIX equivalent is: /cygdrive/c/PROGRA~1/R/R-31~1.2/bin/x64/Rscript.exe
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
R scripting front-end version 3.1.2 (2014-10-31)

Checking system PATH...
C:\PROGRA~1\R\R-31~1.2\bin/x64
c:\Rtools\bin
C:\Octave\3.2.4_gcc-4.4.0\bin
c:\Rtools\gcc-4.6.3\bin
C:\ProgramData\Oracle\Java\javapath
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Python27
C:\Program Files\Lenovo\Bluetooth Software\
C:\Program Files\Lenovo\Bluetooth Software\syswow64
C:\Program Files (x86)\Intel\OpenCL SDK\1.5\bin\x86
C:\Program Files (x86)\Intel\OpenCL SDK\1.5\bin\x64
C:\Program Files\Intel\WiFi\bin\
C:\Program Files\Common Files\Intel\WirelessCommon\
C:\Python27\
JAVA_HOME\bin
C:\Python27\jars\
C:\Python27\Scripts\
C:\Python27\Lib\
C:\Program Files (x86)\Tesseract-OCR
C:\Program Files\MATLAB\R2013b\runtime\win64
C:\Program Files\MATLAB\R2013b\bin
C:\Program Files\MATLAB\R2013b\polyspace\bin
 C:\MinGW\bin\
C:\MinGW\bin
C:\Program Files\TortoiseHg\
C:\Program Files\Intel\WiFi\bin\
C:\Program Files\Common Files\Intel\WirelessCommon\

Checking whether R is a shared library... YES
Checking Rcpp LIBS... 
Checking Rcpp CXXFLAGS... -IC:/Users/MeisamHe/Documents/R/win-library/3.1/Rcpp/include
Checking Octave binary directory... C:/Octave/3.2.4_gcc-4.4.0/bin
Checking Octave Octave bin directory... C:\Octave\3.2.4_gcc-4.4.0\bin
Checking Octave cpp flags... -I/usr/local/octmgw32_gcc-4.4.0-dw2/include
Checking Octave include flags... -IC:\Octave\3.2.4_gcc-4.4.0\include\octave-3.2.4
Checking Octave -L flags... -LC:\Octave\3.2.4_gcc-4.4.0\lib\octave-3.2.4
Checking Octave libraries... -loctinterp
Checking Octave C compiler... gcc
Checking Octave Fortran compiler... mingw32-gfortran-4.4.0-dw2
Checking Octave platform... i686-pc-mingw32
Checking Octave API version... api-v37
Checking Octave version... 3.2.4
Checking whether to infer output names for Octave function (Octave >= 3.4.3?)... no
Checking RcppOctave Octave module directory... C:/Users/MeisamHe/Documents/R/win-library/3.1/RcppOctave/modules
Substituting configure variables (22) in R/config-vars.R
Substituting configure variables (22) in src/Makevars.win
Substituting configure variables (22) in src/modules/Makefile
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture

cygwin warning:
  MS-DOS style path detected: C:/PROGRA~1/R/R-31~1.2/bin/x64/Rscript.exe
  Preferred POSIX equivalent is: /cygdrive/c/PROGRA~1/R/R-31~1.2/bin/x64/Rscript.exe
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
g++ -m64 -std=c++0x -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG -IC:/Users/MeisamHe/Documents/R/win-library/3.1/Rcpp/include -I/usr/local/octmgw32_gcc-4.4.0-dw2/include -IC:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4 -IC:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave -IC:/Octave/3.2.4_gcc-4.4.0/include -DOCT_POST_3_4_0=-1 -fmax-errors=10    -I"C:/Users/MeisamHe/Documents/R/win-library/3.1/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c conversion.cpp -o conversion.o
In file included from rcpp_octave.h:25:0,
                 from conversion.cpp:1:
C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/config.h:1129:0: warning: "_WIN32_WINNT" redefined [enabled by default]
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/_mingw.h:244:0: note: this is the location of the previous definition
In file included from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objbase.h:154:0,
                 from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/ole2.h:16,
                 from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/windows.h:94,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/lo-utils.h:78,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/Array.h:38,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/str-vec.h:31,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/oct-obj.h:32,
                 from rcpp_octave.h:26,
                 from conversion.cpp:1:
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objidl.h:598:52: error: macro "Realloc" requires 3 arguments, but only 2 given
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objidl.h:598:56: sorry, unimplemented: non-static data member initializers
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objidl.h:598:56: error: 'constexpr' needed for in-class initialization of static data member 'Realloc' of non-integral type
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objidl.h:599:25: error: expected identifier before '(' token
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objidl.h:599:25: error: 'parameter' declared as function returning a function
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objidl.h:599:25: error: expected ')' before ',' token
In file included from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/msxml.h:209:0,
                 from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/urlmon.h:219,
                 from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/objbase.h:348,
                 from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/ole2.h:16,
                 from c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/windows.h:94,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/lo-utils.h:78,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/Array.h:38,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/str-vec.h:31,
                 from C:/Octave/3.2.4_gcc-4.4.0/include/octave-3.2.4/octave/oct-obj.h:32,
                 from rcpp_octave.h:26,
                 from conversion.cpp:1:
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/oaidl.h:1890:28: error: expected identifier before '(' token
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/oaidl.h:1890:28: error: 'parameter' declared as function returning a function
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/oaidl.h:1890:28: error: expected ')' before ',' token
make: *** [conversion.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="RcppOctave.dll" WIN=64 TCLBIN=64 OBJECTS="conversion.o rcpp_octave.o"' had status 2
ERROR: compilation failed for package 'RcppOctave'
* removing 'C:/Users/MeisamHe/Documents/R/win-library/3.1/RcppOctave'
Warning messages:
1: running command '"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\MeisamHe\Documents\R\win-library\3.1" "C:/Users/MeisamHe/Desktop/Desktop/Projects/RegretInAuction/VariationalBayesian/vdpgm/RcppOctave_0.14.5.tar.gz"' had status 1 
2: In install.packages(path_to_file, repos = NULL, type = "source") :
  installation of package ‘C:/Users/MeisamHe/Desktop/Desktop/Projects/RegretInAuction/VariationalBayesian/vdpgm/RcppOctave_0.14.5.tar.gz’ had non-zero exit status

**Comment by adalisan** [comment]
As a suggestion, you might want to try octave 3.6
http://wiki.octave.org/Octave_for_Windows#Octave-3.6.4-mingw_.2B_octaveforge_pkgs
In the README, that is the version that is referred to for Octave.
That said, both this version and 3.8  did not work for me on Windows 7 64-bit. I could not build RcppOctave source pkg from CRAN. Rtools 3.1 is installed and the bin directory is in the system PATH.

**Comment by meisamhe** [comment]
Thank you so much adalisan for your suggestion. Actually, I decided to re-implement to code in R, and it was a good experiment.
